### ISSUE TITLE
Custom exception handler and 4xx responses examples in UI

### ISSUE THREAD

**Issue by OttoAndrey** [ghazi-git/drf-standardized-errors#61]
Hi! Thanks for this useful package! I am facing with one issue. 

I am using custom exception handler 

```python
"EXCEPTION_HANDLER": "libs.api.exceptions.custom_exception_handler"
```

I need this one because of `ProtectedError`

```python
def custom_exception_handler(exc, context):

    if isinstance(exc, ProtectedError):
        return protected_error_handler(exc)  # special handler for `ProtectedError`

    return handler.exception_handler(exc, context)  # default handler from `drf-standardized-errors`
```

In this case Redoc/Swagger don't display 4xx examples :(

<img width="483" alt="image" src="https://github.com/ghazi-git/drf-standardized-errors/assets/30920379/ebb3d4e3-4d33-4f9d-bfa8-5c1fc8674b67">

If I use 

```python
"EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler"
```

It works as expected

<img width="450" alt="image" src="https://github.com/ghazi-git/drf-standardized-errors/assets/30920379/5ec8958f-c131-4069-914d-f5eedaf2fd38">

I find out that it happens because of [this](https://github.com/ghazi-git/drf-standardized-errors/blob/f946f1e879d5a6800ca14cfca103c3eed0c601f7/drf_standardized_errors/openapi.py#L89) condition 

```python
    def _should_add_error_response(self, responses: dict, status_code: str) -> bool:
        if (
            self.view.get_exception_handler() is not standardized_errors_handler  # I use custom handler thats why this condition is True
            or status_code in responses
        ):
```

Is it possible to override it but not to copy whole `def _should_add_error_response()`?..

**Comment by ghazi-git** [comment]
Unfortunately, it's like you said, you need to copy the whole method to change that specific condition.
However, that condition is there because the idea is that the `ExceptionHandler` and `ExceptionFormatter` are customizable enough to handle almost everything. Also, I know that [drf docs](https://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling) defines a custom exception handling like you did, but with this package, the customizations should be done by subclassing `ExceptionHandler` and `ExceptionFormatter` instead. That way, you have the ability change specific things about exception handling without having to rewrite the whole exception handler.

Not sure what `protected_error_handler` is doing, but let me give an example. Let's say when a `ProtectedError` is raised by django, you want to always return "409 Conflict" status. In that case, first you need to define a custom drf exception

```python
from rest_framework.exceptions import APIException

class ConflictError(APIException):
    status_code = 409
    default_detail = "Unable to delete this object."
    default_code = "conflict"
```

then you need to define an `ExceptionHandler` subclass and add it to the settings

```python
from django.core.exceptions import ProtectedError
from drf_standardized_errors.handler import ExceptionHandler

class MyExceptionHandler(ExceptionHandler):
    def convert_known_exceptions(self, exc: Exception) -> Exception:
        if isinstance(exc, ProtectedError):
            return ConflictError()
        else:
            return super().convert_known_exceptions(exc)
```

This will result in a response like the below with the status code 409
```json
{
  "type": "client_error",
  "errors": [
    {
      "code": "conflict",
      "detail": "Unable to delete this object.",
      "attr": null
    }
  ]
}
```

You can find [another example in the docs](https://drf-standardized-errors.readthedocs.io/en/latest/customization.html#handle-a-non-drf-exception)

**Comment by OttoAndrey** [comment]
Wow! Thank you! I will try the way like you described
