### ISSUE TITLE
Duplicate errors in response for authentication failures

### ISSUE THREAD

**Issue by omargawdat** [ghazi-git/drf-standardized-errors#86]
## Description
When using the `drf_standardized_errors` package, I'm encountering duplicate error messages in the response for authentication failures. This is causing redundant information to be sent to the client.

## Current Behavior
For authentication failures, the response contains duplicate errors with slightly different information:

```json
{
 "type": "client_error",
 "errors": [
  {
   "code": "authentication_failed",
   "detail": "User is inactive",
   "attr": "detail"
  },
  {
   "code": "authentication_failed",
   "detail": "user_inactive",
   "attr": "code"
  }
 ]
}

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "config.custom_exception_handler.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_SCHEMA_CLASS": "drf_standardized_errors.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "600/day", "user": "2000/day"},
}

**Comment by ghazi-git** [comment]
@omargawdat thank you for opening the issue. It was interesting to look into and would be helpful for others who encounter it in the future.

**The reason behind the issue** is the [custom `AuthenticationFailed` exception defined by simplejwt](https://github.com/jazzband/djangorestframework-simplejwt/blob/d66d246bf56a27aa3e8383ccbee5c7b92a4b10ef/rest_framework_simplejwt/exceptions.py#L41). Simplejwt inherits from drf `AuthenticationFailed`, and [sets `default_detail` as a dict with 2 keys `detail`, `code`](https://github.com/jazzband/djangorestframework-simplejwt/blob/d66d246bf56a27aa3e8383ccbee5c7b92a4b10ef/rest_framework_simplejwt/exceptions.py#L28) . drf then deals with the dict in a similar fashion to receiving validation errors of 2 fields one called `detail` and the other field is `code`. That's why drf-standardized-errors displays 2 errors one with attr detail and the other with attr code. You can see all this if you inspect the auth failed exception from simple jwt
![image](https://github.com/user-attachments/assets/3527c075-0a2b-4449-b7f3-a926d322b5da)

This approach seems to have been implemented to work specifically with the original drf exception handler. That's so that the API client can view the error code (drf does not return an error code when using its default exception handler). Here's the output with the default drf exception handler
```json
{
  "detail": "User is inactive",
  "code": "user_inactive"
}
```

**To work around this**, you can do sth similar to [what's described here](https://drf-standardized-errors.readthedocs.io/en/latest/customization.html#handle-a-non-drf-exception)
```python
from rest_framework.exception import AuthenticationFailed as DRFAuthenticationFailed
from rest_framework_simplejwt.exception import AuthenticationFailed as SimpleAuthenticationFailed
from drf_standardized_errors.handler import ExceptionHandler

class MyExceptionHandler(ExceptionHandler):
    def convert_known_exceptions(self, exc: Exception) -> Exception:
        if isinstance(exc, SimpleAuthenticationFailed):
            return DRFAuthenticationFailed(str(exc.detail["detail"]), code=...)
        else:
            return super().convert_known_exceptions(exc)
```
You'll also want to handle [`InvalidToken`](https://github.com/jazzband/djangorestframework-simplejwt/blob/d66d246bf56a27aa3e8383ccbee5c7b92a4b10ef/rest_framework_simplejwt/exceptions.py#L45) in the same way. It is sometimes raised with [detail as a dict](https://github.com/jazzband/djangorestframework-simplejwt/blob/d66d246bf56a27aa3e8383ccbee5c7b92a4b10ef/rest_framework_simplejwt/authentication.py#L113-L118) which would result in a similar issue

**Comment by omargawdat** [comment]
it works for me, thanks for the explanation!!
